### ISSUE TITLE
Can not use game voice?

### ISSUE THREAD

**Issue by myheartwellgoon** [CS-NextClient/NextClient#25] opened 2024-09-16 01:45 UTC
I use NextClient v2.4.0-beta.4
but can not use game voice
server load revoice_plus_mm.so

**Comment by Polarhigh** [comment] 2024-09-21 10:25
Voice chat doesn't work only on your server or on all servers?
If only on yours, does it work on the regular steam client?

**Comment by myheartwellgoon** [comment] 2024-09-25 13:24
my client is using nosteam NextClient v2.4.0-beta.4 + Goldberg_Lan_Steam_Emu,All players cannot use voice,Can you help me?

**Comment by Polarhigh** [comment] 2024-09-26 12:02
I see. The problem is that goldberg does not implement steam API for voice chat. 
As one of the options you can try to contact the author of goldberg and ask him to add functionality (even borrow code from [revoice](https://github.com/s1lentq/revoice)).

This functionality was not planned to be added to NextClient. Well, we may need to think about it.

**Comment by myheartwellgoon** [comment] 2024-09-26 12:08
I can use voice with nextclient 2.3.5, but it cannot customize some functions, which is very frustrating.

**Comment by myheartwellgoon** [comment] 2024-09-26 12:25
> I see. The problem is that goldberg does not implement steam API for voice chat. As one of the options you can try to contact the author of goldberg and ask him to add functionality (even borrow code from [revoice](https://github.com/s1lentq/revoice)).
> 
> This functionality was not planned to be added to NextClient. Well, we may need to think about it.

This is my dream client, just the voice function is perfect,can you help me?

**Comment by Polarhigh** [comment] 2024-09-27 21:41
NextClient up to version 2.4.0 is supported by other people and contains a proprietary emulator, which is why voice chat works there.
There is no ready-made solution for voice chat functionality using goldberg emulator.

**Comment by myheartwellgoon** [comment] 2024-09-28 01:00
> NextClient up to version 2.4.0 is maintained by others and contains a proprietary emulator, so voice chat works in it. There is no ready-made solution for voice chat functionality using goldberg emulator.

this proprietary emulator be added to NextClient v2.4.0-beta.4 ？It would be great if it works，Thanks

**Comment by Polarhigh** [comment] 2024-10-12 13:46
Sorry for the long long reply 🙏

There are 2 reasons why it can't be added:
1. lack of source code
2. and the most important one, we don't want to deal with pirate software, and steam emulator falls under this category

**Comment by myheartwellgoon** [comment] 2024-10-13 03:33
It was so frustrating, so close to being perfect, that you were able to isolate nextclient's steamapi and use it?

**Comment by Polarhigh** [comment] 2024-10-14 11:11
I'm not quite sure what you mean.... If you mean whether you can adapt the emulator from version 2.3.5, you can, but I suppose you will need some modifications in the code base.

**Comment by myheartwellgoon** [comment] 2024-10-14 12:23
I want to use the 2.4.0 functionality and the 2.3.5 steamapi

**Comment by Polarhigh** [comment] 2024-10-27 10:58
Closed in favor of #29

**Closed by Polarhigh** 2024-10-27 10:58 UTC
